### ISSUE TITLE
Default admin user and password needed 

### ISSUE THREAD

**Issue by rhc** [johnkyony/internal_orders#1]
Problem: For the moment, a change in the source code is needed to create the first admin. 

Other advantage: The admin user can be used in testing

**Comment by johnkyony** [comment]
Okay shall create a user admin as a seed data

**Comment by rhc** [comment]
It will be nice If you can also include default types and departments

**Comment by johnkyony** [comment]
Yeah i am creating that in the seeds.rb right now

**Comment by johnkyony** [comment]
done just pushed the solutions
