### ISSUE TITLE
Department and type field not displaying properly in orders database

### ISSUE THREAD

**Issue by johnkyony** [johnkyony/internal_orders#2]
The department and type field in the orders are not displaying properly in the index of the orders model 

![orders_field](https://cloud.githubusercontent.com/assets/4305153/12035116/a8b2ee50-ae39-11e5-87f6-bb762fc705a2.png)

**Comment by rhc** [comment]
Problem solved by adding the name field. 
See changes in app/views/orders/_order_list.html.haml
